UBER-2644 Add Plugin Logger documentation.
TeamUbersmith/plugins-docs pull request #4
Opened 2019-01-11 19:05 UTC by donoage

* Add Plugin Logger documentation.
* also added **table of contents** for big markdown files.

2019-01-11 19:25 UTC, michaelpwest approved these changes

2019-01-22 13:40 UTC, camyangelo commented on docs/DEVELOPMENT.md
> -* Additional PHP files that the bootstrap file includes.
no period at the end

2019-01-22 13:41 UTC, camyangelo commented on docs/DEVELOPMENT.md
> -* Datasource classes.
no period at the end

2019-01-22 13:41 UTC, camyangelo commented on docs/DEVELOPMENT.md
> -* JavaScript files.
no period at the end

2019-01-22 13:41 UTC, camyangelo commented on docs/DEVELOPMENT.md
> -* CSS files.
no period at the end

2019-01-22 13:41 UTC, camyangelo commented on docs/DEVELOPMENT.md
> -* Any additional files the plugin needs (for example, images).
no period at the end

2019-01-22 13:42 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +* Additional PHP files that the bootstrap file includes.
no period at the end

2019-01-22 13:43 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +* Datasource class files.
no period at the end

2019-01-22 13:43 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +* JavaScript files.
no period at the end

2019-01-22 13:43 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +* CSS files.
no period at the end

2019-01-22 13:43 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +* Any additional files the plugin needs (for example, images).
no period at the end

2019-01-22 13:44 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +## Writing your plugin
Capitalize  Your and Plugin

2019-01-22 13:46 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +A datasource requires a class implementing the `UbersmithSDK\Usage\Data\Source` interface as well as some annotations. For more information about the functions available to use, [see Datasources]().
A datasource requires a class implementing the `UbersmithSDK\Usage\Data\Source` interface as well as some annotations. For more information about the available functions, [see Datasources]().

2019-01-22 13:46 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +### Resource types
Capitalize Types

2019-01-22 13:48 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +Plugin Logger is available for use to track what PluginSystem hooks are being fired and how your plugins are reacting to them.
Plugin Logger tracks what PluginSystem hooks are being fired and how your plugins are reacting to them.

2019-01-22 13:49 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +- Now the logger is enabled and you should see _Go to Logger_ link to access the logger.
- Now the logger is enabled and you should see the _Go to Logger_ link to access the logger.

2019-01-22 13:50 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +| `datetime` | datetime of log event. |
no period at end

2019-01-22 14:17 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +| `message` | message is composed of `[event_origin] event_description` |
need period at end.

2019-01-22 14:18 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +| `plugin` | `identifier` from specified in manifest.json, the plugin's `module_name` and `function` related to the event. |
seems a word is missing here... what is specified?

2019-01-22 14:19 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +- A log message with ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `RED` background color indicates a successful execution of a plugin function.
does both green and red mean "success"? Is read failed?

2019-01-22 14:20 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +###### View options
Capitalize Options

2019-01-22 14:21 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +- You can filter per plugin and/or per usage on left sidebar navigation radio buttons.
change on to with

2019-01-22 14:21 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +###### Text search
Capitalize Search

2019-01-22 14:22 UTC, camyangelo commented on docs/DEVELOPMENT.md
> +###### Clearing the log view
Capitalize Log and View

2019-01-22 14:22 UTC, camyangelo commented on docs/functions/FUNCTIONS.md
> +## Debug functions
Capitalize Functions

2019-01-22 14:24 UTC, camyangelo requested changes
Have inline comments for you.

2019-01-29 19:45 UTC, donoage commented
@camyangelo All updates have been made. Thanks Camille 🎉  Let me know if there's anything else.

2019-01-31 15:50 UTC, camyangelo commented
@donoage - you are most welcome!

2019-01-31 19:19 UTC, camyangelo approved these changes

2022-10-08 22:24 UTC, closed without merging